// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEpnt2rynvSMge9tmmUUbbt-qhknfDiGw',
    appId: '1:197519269759:web:31499919b2d58cbadac44a',
    messagingSenderId: '197519269759',
    projectId: 'say-sense',
    authDomain: 'say-sense.firebaseapp.com',
    storageBucket: 'say-sense.firebasestorage.app',
    measurementId: 'G-3474NSYGWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTMxEoJFFZOYvt_y6R2jQvYIq5-xQuwWw',
    appId: '1:197519269759:android:1664ef7be896efbddac44a',
    messagingSenderId: '197519269759',
    projectId: 'say-sense',
    storageBucket: 'say-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEq00z4ZumhbO0u3Y6i5qHefpVHLd-TpY',
    appId: '1:197519269759:ios:6fa3d2427a535296dac44a',
    messagingSenderId: '197519269759',
    projectId: 'say-sense',
    storageBucket: 'say-sense.firebasestorage.app',
    iosBundleId: 'com.example.sense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEq00z4ZumhbO0u3Y6i5qHefpVHLd-TpY',
    appId: '1:197519269759:ios:6fa3d2427a535296dac44a',
    messagingSenderId: '197519269759',
    projectId: 'say-sense',
    storageBucket: 'say-sense.firebasestorage.app',
    iosBundleId: 'com.example.sense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEpnt2rynvSMge9tmmUUbbt-qhknfDiGw',
    appId: '1:197519269759:web:f07035942eb29b2ddac44a',
    messagingSenderId: '197519269759',
    projectId: 'say-sense',
    authDomain: 'say-sense.firebaseapp.com',
    storageBucket: 'say-sense.firebasestorage.app',
    measurementId: 'G-5S16GG58PR',
  );
}
